# Generated by Django 5.0.6 on 2024-07-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='crated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lista',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
