# Generated by Django 5.0.6 on 2024-07-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_lista_crated_at_lista_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
